language: scala

jobs:
 include:
  - stage: test
    script: sbt ++$TRAVIS_SCALA_VERSION test publishSigned
  - stage: release
    script: sbt ++$TRAVIS_SCALA_VERSION sonatypeRelease

stages:
 - test
 - name: release
   if: tag IS present

env:
 global:
  - secure: "aWUxWfBmq0WDliJKOo1/SGW4cR48a56MjZVI/E2QiCgXCzidQrTcacdVTGnRmP6Jni81lNAp9Ummf67y2jkrUKgiumdllaQ5kPepu6BFDmquni6+F/XJZFFFDJwOu9eMpvWCiTC9lvu6m61i4/BN9R/Hp5qtsMMajaPSf2D2VbF4R6ZR2mu2OE7553Ukg16V8gI6PU+Shb6EqQYR5PLN3GnZNqC7LbkcVBOEJ4+LcmnzH2otOnX8kFxnzKZtmiPH9eVPgVkHPj+MsZJ4YugqoMXvD03iYPM9KBFb+CGFvWdiOms6jynJ/XWMScNS8ykFAMHo75zZgNhPNL/bVcDh0Ckebbk0pynPtnePKBL5HwtjCLIIlLb1FgsTv9uLuk1Mgp0+0zJ7JYgXluvEyVPWqx+A0PaPo42uIdhUz4I6MfWZyAKeg0cqDfj4lHQ73GB+BiuSnj7kDqF5ZB/r8S7S3VzFC4UFymUKeIxaY8THyCqK4rNbl7Cdj8T/+/UFXTYskAbu8Q5MLl/9+6UIxrN6TJFR9tNzquTD/cEnZ53RH2vlwXq+sozxNg6i1ayQts4ldKfpyvyS0iy6VGGKku7jCEAZM3ZXJAgwDyOk4ycoZUxD1wN4Lziz2iNof9id2s6HBiQFzFy0BqzE0Ggj0VxxnXEpbPccww76sp9l8ZST+sM="
  - secure: "VljFgDm4NWd/sE78WAqvXSdU2wJJiVX31sOKm8IzQCh7vNqzg6k04ADQzxNkeN0iyHLQ4ggPHwVEEAN9uiTdtrC5lte23MXjsAgUEE8ODcPaiKZAjk7+PxjH52MdJpG+8jPAtLaTvkemo9rnQlX7Wa2VFCqyPkiw4ia5O/JOiQWmyTMAaGS10nWzFs8Ayq5O1r+lWEn3J/h0zQWA9Di+AB6hPQvct06ZGbpaMkjwCUKsHpPiJBpfBooINoEMjS3gVjVcAHGC8EXw+db2GcI8QhATq7gKQvOIPUZJwVAxMNAgKVW9e+RAVakPM6m3w/lf+qc517F1YOw+5T9t9NEde7nICO1HEqaOWQ65wHyHWrED3iUKOfKIDe1eUP83zVXnsNtkWvJqOoaDSuxUAuopu7iy9YE4kXqgAnFYYus8RppSCOhn/Yp3xBgWd8BF4Jc/cIFlxOYkeYWMkgrSbwzjQAfYAue9d3rQRGE0fdzIhZip0MvmAJWxF5Y6vc2ryiV5fIxQ6cit6YjyPkq1Mi6asrFOL9xf+tfTHcLlF2JGMej3XyeSHjastdmUZyeCR8HwVnCjmQWGV9tv8P2e72nOfqVu5CMCJ1nAl9LBhaw5k4UFQffsrr89G73qye01jGAwGE8QrlbGPMq3fVAEOTG4CVuw7h+nCwry/klY893SpVQ="
  - secure: "XjHWY/vmkrp7Gcbx+WRHxAASY0C+ENjHik/SBdUTuhOrpEzarxA1J8tWTnRveUSYwQk7Rm58OZOO5KEkh/Ck4qITiDf/Puev1shbkey5git1K4LZ6xSRiQnxItoUjrAi3z/+thxsLPx3qscLnDDETiJYnMEZ0mouZVaMG1Q+LF2i4ynZB9HOe7GL1QN5PpCfHH0NTmly5ePaAfk1UnFS+e+rmoDpkJSCRHlK+i+mp+wZUmRuBhUizMh7sXX7MlK+QLbLxUGrRVGODAshPPHf5fU9glk59M5mX3xkFlqiqLvjtYO1VrjqtZkSP0m++pQ5IOnO//4SsLQUyv8d6nV0qjxs5XrQyOCmhjRTHY4a+gE3McOIWsVh/TlMJsZ5Nqc/VcIZigij7T2KyySo0l6lP96ngwMcJTtkf3hT/w4MSMAFctD9zATbFkkll/EfXiyox7pn0nhmhjuZBMEIRQqzolQgmW2Jk1i84y174ErmXCDeGGcfLU2w792nrxMVDB1YEhpbyph7waihw9xriLKHlPq4gv/Ga/qS8D4w26ToN6TzSHckcpHQaiMgfxnBGpGQ9wZGnmffdEKO/f/iGHFPU1zAEmfU07prPDAzSyCcaQCWGhYpZ1AV70qowKueAGPDAlubAEv/wMtaCwgoS9zxMY+X8CFh5nrvj4JA1DGIDzM="
